sudo: required
services:
  - docker

before_install:
  - docker build -t kazu884/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kazu884/react-test npm test -- --coverage

after_success:
  - docker build -t kazu884/multi-docker-client ./client
  - docker build -t kazu884/multi-docker-nginx ./nginx
  - docker build -t kazu884/multi-docker-server ./server
  - docker build -t kazu884/multi-docker-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kazu884/multi-docker-client
  - docker push kazu884/multi-docker-nginx
  - docker push kazu884/multi-docker-server
  - docker push kazu884/multi-docker-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-2-817650554067
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY